### ISSUE TITLE
TypeError: Cannot read property 'grey' of undefined

### ISSUE THREAD

**Issue by hsxiaoma** [staticfile/cli#17]
C:\Users>sfile lodash
 搜索 lodash 共有 2 个库，当前列出 2 个:
C:\Program Files\nodejs\node_modules\sfile\bin\sfile:178
          list.add(lib, lib.base + lib.subLabel.grey);
                                               ^

TypeError: Cannot read property 'grey' of undefined
    at C:\Program Files\nodejs\node_modules\sfile\bin\sfile:178:48
    at Array.forEach (native)
    at C:\Program Files\nodejs\node_modules\sfile\bin\sfile:170:19
    at Request._callback (C:\Program Files\nodejs\node_modules\sfile\lib\index.j
s:7:12)
    at Request.self.callback (C:\Program Files\nodejs\node_modules\sfile\node_mo
dules\request\request.js:129:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Program Files\nodejs\node_modules\sfile\node_modu
les\request\request.js:873:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)

**Comment by ByteRax** [comment]
+1

**Comment by think2011** [comment]
```
➜  desktop sfile jquery
 搜索 jquery 共有 10 个库，当前列出 10 个:
/Users/think2011/.nvm/versions/node/v7.8.0/lib/node_modules/sfile/bin/sfile:178
          list.add(lib, lib.base + lib.subLabel.grey);
                                               ^

TypeError: Cannot read property 'grey' of undefined
    at /Users/think2011/.nvm/versions/node/v7.8.0/lib/node_modules/sfile/bin/sfile:178:48
    at Array.forEach (native)
    at /Users/think2011/.nvm/versions/node/v7.8.0/lib/node_modules/sfile/bin/sfile:170:19
    at Request._callback (/Users/think2011/.nvm/versions/node/v7.8.0/lib/node_modules/sfile/lib/index.js:7:12)
    at Request.self.callback (/Users/think2011/.nvm/versions/node/v7.8.0/lib/node_modules/sfile/node_modules/request/request.js:129:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/think2011/.nvm/versions/node/v7.8.0/lib/node_modules/sfile/node_modules/request/request.js:873:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)
```

看样子没人维护了，太可惜了

**Comment by li2go** [comment]
TypeError: Cannot read property 'grey' of undefined
    at /usr/local/lib/node_modules/sfile/bin/sfile:178:48
    at Array.forEach (native)
    at /usr/local/lib/node_modules/sfile/bin/sfile:170:19
    at Request._callback (/usr/local/lib/node_modules/sfile/lib/index.js:7:12)
    at Request.self.callback (/usr/local/lib/node_modules/sfile/node_modules/request/request.js:129:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/sfile/node_modules/request/request.js:873:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)
